### ISSUE TITLE
Doorbird connection error

### ISSUE THREAD

**Issue by heni1** [iobroker-community-adapters/ioBroker.doorbird#108]
It is not possible to connect to the Doorbird from a Docker container in the MACVLAN.
The log shows:
Error in testBird() Request: AxiosError: Request failed with status code 401

![grafik](https://github.com/iobroker-community-adapters/ioBroker.doorbird/assets/3791048/d333416b-9220-485e-ab1d-69edde23bebe)

![grafik](https://github.com/iobroker-community-adapters/ioBroker.doorbird/assets/3791048/c997cb09-3a83-4afd-98cc-9b02e0d2c031)

open docker ports in MACVLAN Container
![grafik](https://github.com/iobroker-community-adapters/ioBroker.doorbird/assets/3791048/157441c9-47b5-4bbd-a1bb-3b1c2653be23)

**Versions:**  
 - Adapter version: v1.3.0
 - JS-Controller version: 5.0.17
 - Node version: V18.19.0
 - Operating system: Synology Docker

**Additional context**  
The instructions do not provide any information about the required ports and what exactly the DoorBird Device ID should be.

**Comment by Schmakus** [comment]
@Stefan592 any idea? I have no experience with docker.

**Comment by heni1** [comment]
Where can I find the DoorBird Device ID? On which ports is the adapter listening? Can more be logged out than status code 401 (Unauthorized Access)? I can log in to https://webadmin.doorbird.com/ with the user name and password.

**Comment by Schmakus** [comment]
The device id are the first 6 letters of any user. e.g. ghxxxx
Port: UDP 35344 (see at logging)

**Comment by heni1** [comment]
OK, that's how I entered it. Why could the test step fail? The ports that I have enabled are attached. What could I do to find the problem?

**Comment by Schmakus** [comment]
Access rights for the used user are correct? API Operator and Live Video?

**Comment by heni1** [comment]
I have created a new user at https://webadmin.doorbird.com/ and given this user the API Operator rights.
Now the connection test works. The Admin User account does not work!!!

![grafik](https://github.com/iobroker-community-adapters/ioBroker.doorbird/assets/3791048/32eee4d2-b4ed-47f4-ab3d-c8eeb94745e6)
