### ISSUE TITLE
Bilddatei wird erzeugt, jedoch kein Inhalt

### ISSUE THREAD

**Issue by quorle** [iobroker-community-adapters/ioBroker.doorbird#21]
Es wird nun ein Bildobjekt erzeugt unter /opt/iobroker/iobroker-data jedoch hat dies keinen Inhalt und eine Größe von 0 KB.
Ich habe den Adapter bereits deinstalliert und neu installiert.

NPM: 6.14.16
Node.js: v14.19.0
Plattform: linux
Adminversion: v5.3.1
js-controller: 4.0.15

![Unbenannt](https://user-images.githubusercontent.com/38273154/155036326-1dbeef39-f8bd-4ce4-aaaa-06767797e71b.JPG)

**Comment by Schmakus** [comment]
mit v1.0.0 werden die Snapshots neu gespeichert und sind unter den ioBroker Files zu finden.
