### ISSUE TITLE
Move adapter to community?!

### ISSUE THREAD

**Issue by klein0r** [iobroker-community-adapters/ioBroker.doorbird#23]
https://github.com/iobroker-community-adapters/info#add-git-repo-to-organization

**Comment by klein0r** [comment]
@BuZZy1337 Ping

**Comment by klein0r** [comment]
@BuZZy1337 Pong

**Comment by Negalein** [comment]
> @BuZZy1337 Pong

ich glaube, der macht nichts mehr. Ist schon ewig inaktiv!

**Comment by klein0r** [comment]
Hatte gehofft, dass er wenigsten Mail-Notifications an hat

**Comment by mcm1957** [comment]
Adapter has been moved 06/2023.
