### ISSUE TITLE
Peripherie zum Adapter hinzufügen

### ISSUE THREAD

**Issue by Hant0r** [iobroker-community-adapters/ioBroker.doorbird#24]
Wäre es möglich, auch die an Doorbird angeschlossene Peripherie, wie ein Gong, im Adapter hinzuzufügen.
Ich würde deren Einstellungen gerne auch über ioBroker steuern können.

Beispiel:
Setze die Lautstärke des Gongs auf ein Minimum wenn das Kind schläft.

**Comment by Schmakus** [comment]
Die Doorboord-API gibt das leider nicht her.
