### ISSUE TITLE
No Doorbell Trigger Variable Update

### ISSUE THREAD

**Issue by creecool** [iobroker-community-adapters/ioBroker.doorbird#26]
Since 27.02.2023, the doorbell and motion trigger created by the app are no longer controlled. 
(http://192.168.x.x:8100/ring?)
Instance has already been reinstalled, but without change. HTTP requests via SimpleAPI works. Does anyone else have this problem?
DoorBird FW: 138 / Model D2101V
IOB: 0.1.5

**Comment by OberfragGER** [comment]
> schedules are correctly defined in the doorbird app?

I just installed the Doorbird-Adapter in Version 0.1.5 with Doorbird FW 141. Same issue here.
Its my 2nd Doorbird@home. this one with a Keypad. The URL for the keypad and motion as well was automatically installed, but not the ring. :(

**Comment by Schmakus** [comment]
URL for Keypad? I think, the Adapter did not support keypads?!
Do you have any screenshots about you favorites (Doorbird App)
BTW: v1.0.5 is available.

**Comment by OberfragGER** [comment]
> URL for Keypad? I think, the Adapter did not support keypads?! Do you have any screenshots about you favorites (Doorbird App) BTW: v1.0.5 is available. (Latest repo)
> 
> And last: are the schedules in the Doorbird app correctly defined? Is the favorite "http://192.168.x.x:8100/ring?1) available? Is the schedule for doorbell "http://192.168.x.x:8100/ring?1" activated? Hole day?

Okay. Ringing is working again. But the snapshot from ringing is just 1kb big. :(
I copied some things from the Instance Doorbird.0 to Doorbird.1 (my new Doorbird).
I thing i did´nt set up the shedule.

But what i did in the App - setup the Keycode "240477" and the instance.1 automatically created the data point and url.
![image](https://github.com/iobroker-community-adapters/ioBroker.doorbird/assets/28652993/2c746bc5-a350-45a9-b5d4-bb364f19625e)

But the data point get not activated. I will try simple url the the keypad things

**Comment by Schmakus** [comment]
Use v1.0.5 from latest repo. 
The file handling has changed.

**Comment by OberfragGER** [comment]
> Use v1.0.5 from latest repo. The file handling has changed.

I have deleted the picture 1.snap.jpg. The update to 1.0.5.
Ringing is working, keypad is also working!
![image](https://github.com/iobroker-community-adapters/ioBroker.doorbird/assets/28652993/9616b4b4-f7d8-4e19-b8cb-3f48321f475d)

But no picture gets created in iobroker-data on buttonpress :(. The user has access to "everything".
![image](https://github.com/iobroker-community-adapters/ioBroker.doorbird/assets/28652993/115e1046-4c32-4912-92c6-565eac38c561)

These are my http-calls:
![image](https://github.com/iobroker-community-adapters/ioBroker.doorbird/assets/28652993/926c862d-8eef-4618-b7d2-5105c82c1468)

**Comment by OberfragGER** [comment]
> Use v1.0.5 from latest repo. The file handling has changed.

Ok. I found the files in a whole diffent fiolder!
/opt/iobroker/iobroker-data/files/doorbird.1

**Comment by Schmakus** [comment]
👍
Yes, the file handling has changed because js-controller 5. the old one was deprecated. 
RFID handling is planned. 

I didn't know, that the keypad is similar handled by the Doorbird API as a doorbell. 
I will update the documentation.

**Comment by OberfragGER** [comment]
> I didn't know, that the keypad is similar handled by the Doorbird API as a doorbell. I will update the documentation.

So great that you code handles this instanly!
