### ISSUE TITLE
DoorBird D301A

### ISSUE THREAD

**Issue by soyyo1978** [iobroker-community-adapters/ioBroker.doorbird#30]
Is the D301A not compatible? Adapter ist not able to connect.

**Comment by Schmakus** [comment]
<div class="page" title="Page 4" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><div class="layoutArea"><div class="column"><p><span style="font-size: 14pt; font-family: DejaVuSans; font-weight: 700; color: rgb(0, 132, 209);">COMPATIBLE DEVICES</span></p></div></div>

Device | Hardware version | Firmware version
-- | -- | --
DoorBird Video Door Station D10x | 1.00 and above | 000099 and above
DoorBird Video Door Station D20x | 1.00 and above | 000099 and above
DoorBird Video Door Station D21x | 1.00 and above | 000108 and above
BirdGuard B10x | 1.00 and above | 000099 and above
DoorBird Video Door Station D11x | 1.00 and above | 000130 and above

</div>
