### ISSUE TITLE
Fix errors reported by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.doorbird#36]
Erroro reported by adapter checker
- [ ] :heavy_exclamation_mark: [E019] Invalid repository URL in [package.json](https://github.com/iobroker-community-adapters/ioBroker.doorbird/blob/master/package.json): https://github.com/BuZZy1337/ioBroker.doorbird. Expected: git@github.com:iobroker-community-adapters/ioBroker.doorbird.git or https://github.com/iobroker-community-adapters/ioBroker.doorbird.git
- [ ] :heavy_exclamation_mark: [E150] No common.connectionType found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.doorbird/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E152] No common.dataSource found in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.doorbird/blob/master/io-package.json)
- [ ] :heavy_exclamation_mark: [E154] common.dependencies must contain [{"js-controller": ">=2.0.0"}] or later - recommended: [{"js-controller": ">=3.3.22"}]
- [ ] :heavy_exclamation_mark: [E405] Icon must be in the following path: https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.doorbird/master/
- [ ] :heavy_exclamation_mark: [E407] Meta URL (latest) must be equal to https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.doorbird/master/io-package.json
- [ ] :eyes: [W171] "common.title" is deprecated in [io-package.json](https://github.com/iobroker-community-adapters/ioBroker.doorbird/blob/master/io-package.json)
- [ ] :eyes: [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W113] Adapter should support compact mode
- [ ] :eyes: [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] :eyes: [W202] Version of [package.json](https://github.com/iobroker-community-adapters/ioBroker.doorbird/blob/master/package.json) (0.2.0-alpha.0) doesn't match latest version on [NPM](https://www.npmjs.com/package/iobroker.doorbird) (0.1.5)

**Comment by Schmakus** [comment]
fix with re-new adapter
