### ISSUE TITLE
[js-controller5] /opt/iobroker/node_modules/iobroker-data wurde gelöscht

### ISSUE THREAD

**Issue by Klaus-Lucas** [iobroker-community-adapters/ioBroker.doorbird#38]
Während eines Updates von iobroker scheint das Verzeichnis /opt/iobroker/node_modules/iobroker-data gelöscht zu werden.
Daher kann der Adapter die Bilder nicht mehr ablegen und stürzt ab.
Adapter    "admin"        : 6.5.8    , installed 6.5.8
Adapter    "doorbird"     : 0.1.5    , installed 0.1.5

2023-06-15 06:47:45.738  - error:  doorbird.0 (12974) uncaught exception: ENOENT: no such file or  directory, open  '/opt/iobroker/node_modules/iobroker-data/doorbird.0.snap.jpg'
2023-06-15 06:47:45.742  - error:  doorbird.0 (12974) Error: ENOENT: no such file or directory, open  '/opt/iobroker/node_modules/iobroker-data/doorbird.0.snap.jpg'
2023-06-15 06:47:45.743  - error:  doorbird.0 (12974) Exception-Code: ENOENT: ENOENT: no such file or  directory, open  '/opt/iobroker/node_modules/iobroker-data/doorbird.0.snap.jpg'
2023-06-15 06:47:45.752  - warn: doorbird.0 (12974) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-06-15 06:47:46.492  - error: host.iobroker instance system.adapter.doorbird.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

**Comment by mcm1957** [comment]
M.E. hat das Verzeichnis unter node_modules absolut nichts verloren.

**Comment by Klaus-Lucas** [comment]
js-controller: 5.0.3
Node.js: v18.16.0
Ich kann in der Config des Adapters nichts eingebn, was den Pfad beeinflusst.

**Comment by mcm1957** [comment]
Die Github Version 0.2.0 sollte den Fix für js-controller5 beinhalten.
Könntest du diese bitte mal mit js-controller 5 **auf einem TESTSYSTEM** installieren?
(Übliche Warnung: Backup checken!, Nicht auf produktiven System!)

Wenn die bei dir läuft, lass ich sie als latest los. Mangels Testsystem will ich das allerdings nicht tun ohne irgendeine positive Rückmeldung.

**Comment by mcm1957** [comment]
Nur zur Sicherheit:

a) Das ist das Logfile der Installation - und nicht des Starts - seh ich das richtig?

b) Hast du eine GITHUB Installation (Katze im Expert Mode) versucht? Diese Release ist nicht auf npmjs verfügbar. Mich irritiert dass im Log etwas auf npmjs gesucht wird. Dort ist noch eine Vorgängerversion die auch noch auf das alte Repo verweist.

Falls die GH Installation crasht - sorry. Muss mir das dann ansehen oder schaun wer Zeit hat. Kann bei mir aber noch bis übernächste Woche dauern da ich nächste Woche offline bin.

**Comment by Klaus-Lucas** [comment]
1) Ja
2) Ja. Unter Adapter bei Doorbird dir 3 Punkte und dann das + gewählt
Bitte wählen Sie eine bestimmte Version von doorbird aus

0.2.0-alpha.0

    Adapter has been moved into iobroker-community-adapters-area
    Github actions and testing has been added
    standard development tools have been added
    dependencies have been upgraded

3) eilt nicht :-)

**Comment by mcm1957** [comment]
Nö so geht das nicht. Wundert mich dass du die Version auswählen kannst.
Bitte direkt von Github installieren:
![image](https://github.com/iobroker-community-adapters/ioBroker.doorbird/assets/28575778/1722b00b-22b8-4a84-9345-19c0d435f538)

Url: https://github.com/iobroker-community-adapters/ioBroker.doorbird

**Comment by mcm1957** [comment]
Ok, installation geht mal.
Und scheinbar läuft er auch - zumindest humpelnd :-)
Ich check mal was ich zu den Verzeichnissen finde.

**Comment by mcm1957** [comment]
@Klaus-Lucas 
Kannst du mal schaun ob heir was liegt:

...\ioBroker\iobroker-data\doorbird.0

wobei ioBroker dein ioBroker Basisverzeihnis wäre, als z.b: c:\ioBroker, /opt/ioBroker etc. / od \ je nach OS bitte.

Ich hab leider keine Möglichkeit Bilder aktiv anzulegen.

**Comment by Schmakus** [comment]
@mcm1957 ich würde mich nach meinem Urlaub drum kümmern. Wie auch alles andere was noch zu tun ist. Grüße

**Comment by mcm1957** [comment]
Ok, dann hast du den Ball :-)
Im Prinzip funktio niert der Adapter wenn ich es richtig verstanden habe.
Fraglich ist nur of der Hint / Description noch passt.

**Comment by mcm1957** [comment]
Ich zieh dann mal als erste Hilfe ne 0.2.0 ein.
Sobald @Schmakus dann den Adapter und die anderen offenen Issue angeht, gibts neue Version(en)

**Comment by Schmakus** [comment]
fix with re-new adapter
Snapshots nun verfügbar in den ioBroker Files
