### ISSUE TITLE
AxiosError

### ISSUE THREAD

**Issue by todde99** [iobroker-community-adapters/ioBroker.doorbird#55]
After updating to version v1.0.0 (also v1.0.2) I'm getting these warnings in the IOBroker protocol and motions are not captured anymore:

 warn: doorbird.0 (2429106) Error in creating schedule: AxiosError: Request failed with status code 400
 warn: doorbird.0 (2429106) Error in setting Motion schedule: AxiosError: Request failed with status code 400

This was working with the last version.

**Comment by Negalein** [comment]
bekomme auch seit 1.0.0 folgende Meldungen

```
2023-07-05 01:37:22.598  - [33mwarn[39m: doorbird.0 (47333) Found a duplicate favorite! (ID : '0') URL http://10.0.1.202:8100/ring?102
2023-07-05 01:37:22.855  - [33mwarn[39m: doorbird.0 (47333) Found a duplicate favorite! (ID : '1') URL http://10.0.1.202:8100/ring?101
2023-07-05 01:37:23.172  - [33mwarn[39m: doorbird.0 (47333) Found a duplicate favorite! (ID : '2') URL http://10.0.1.202:8100/motion
2023-07-05 01:37:23.682  - [33mwarn[39m: doorbird.0 (47333) Error in creating schedule: Error: Request failed with status code 400
2023-07-05 01:37:23.736  - [33mwarn[39m: doorbird.0 (47333) Error in creating schedule: Error: Request failed with status code 400
2023-07-05 01:37:23.848  - [33mwarn[39m: doorbird.0 (47333) Error in setting Motion schedule: Error: Request failed with status code 400
2023-07-05 01:40:24.176  - [33mwarn[39m: doorbird.0 (47333) Error in creating schedule: Error: Request failed with status code 400
2023-07-05 01:40:24.229  - [33mwarn[39m: doorbird.0 (47333) Error in creating schedule: Error: Request failed with status code 400
```

**Comment by Schmakus** [comment]
Das Problem habe ich auch. Es muss am Umbau von "request" zu "axios" liegen. Die Logik habe ich ansonsten 1:1 übernommen.
**Ein Adapter Neustart behebt das Problem**. Ich bin der Logic zur Prüfung von Duplikaten noch nicht ganz durchgestiegen.
Axios meldet den Fehler, weil es letzlich keine Duplikate gibt, obwohl die Logik diese feststellt.

**Comment by Negalein** [comment]
> Ein Adapter Neustart behebt das Problem

nach Neustart bleibt der Fehler

```
doorbird.0 2023-07-05 08:54:35.709	warn	Error in setting Motion schedule: Error: Request failed with status code 400
doorbird.0 2023-07-05 08:54:35.554	warn	Error in creating schedule: Error: Request failed with status code 400
doorbird.0 2023-07-05 08:54:35.520	warn	Error in creating schedule: Error: Request failed with status code 400
doorbird.0 2023-07-05 08:54:35.128	warn	Found a duplicate favorite! (ID : '2') URL http://10.0.1.202:8100/motion
doorbird.0 2023-07-05 08:54:34.835	warn	Found a duplicate favorite! (ID : '1') URL http://10.0.1.202:8100/ring?101
doorbird.0 2023-07-05 08:54:34.537	warn	Found a duplicate favorite! (ID : '0') URL http://10.0.1.202:8100/ring?102
doorbird.0 2023-07-05 08:54:33.123	info	starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.doorbird, node: v16.20.1, js-controller: 4.0.24
doorbird.0 2023-07-05 08:54:28.287	info	Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
doorbird.0 2023-07-05 08:54:28.287	info	terminating
doorbird.0 2023-07-05 08:54:28.286	info	Got terminate signal TERMINATE_YOURSELF
```

**Comment by Schmakus** [comment]
@Negalein was zeigt deine DoorBird App? Welche Favoriten und Zeitpläne sind dort angelegt?
Wie gesagt, hatte ich dasselbe Problem, aber mit Neustart Adapter verschwunden. Ich arbeite daran.
Ansonsten zurück auf die 0.2.0 wechseln. Diese Version funktioniert ja anscheinend.

**Comment by todde99** [comment]
Bei mir kommt auch nach einem Restart immer noch die Warnings. In der App sind unter HTTP(S) Aufrufe keine Einträge mehr vorhanden.
Falls ich noch was testen kann, gerne!

**Comment by Negalein** [comment]
> was zeigt deine DoorBird App? Welche Favoriten und Zeitpläne sind dort angelegt?

sind nur noch meine RFID da 

![image](https://github.com/iobroker-community-adapters/ioBroker.doorbird/assets/45309436/d12514f9-c234-4559-8ad0-4b3c6bcf432b)

**Comment by Schmakus** [comment]
Ich bringe im laufe des Tages einen Hotfix mit einer neuen Version raus, bei dem das Löschen von nicht vorhandenen Duplikaten unterbunden wird.

**Comment by Schmakus** [comment]
v1.0.4 sollte das löschen nun unterbinden. Es wird jedoch eine Warnung ausgeworfen. Zum Testen entweder direkt von nem installieren oder warten bis es in der beta-repo auftaucht.

**Comment by Schmakus** [comment]
Bezüglich den Snapshots die Doku gelesen, bzw. Mit der Installation auf 1.0.0 hast den Hinweis sogar bestätigt! 😜

**Comment by todde99** [comment]
> Bezüglich den Snapshots die Doku gelesen, bzw. Mit der Installation auf 1.0.0 hast den Hinweis sogar bestätigt!

Wer lesene kann ...!!

Vielen Dank für das schnelle Fixen und überhaupt für das Weiterentwickeln des Adapters! 🥇

**Comment by Schmakus** [comment]
mit v1.0.5 sollte der Fehler gänzlich weg sein und das Löschen von Duplikaten funktioniert wieder!
