### ISSUE TITLE
Bilder werden nicht abgeholt

### ISSUE THREAD

**Issue by quorle** [iobroker-community-adapters/ioBroker.doorbird#56]
Im Bild ist zu sehen, dass die Bilder (egal ob "Snapshot", "Klingel", oder "Motion") nicht abgeholt werden.

Zeitpläne wurden alle nochmals ordentlich erstellt und in die Doorbirdapp eingetragen. 
Im Log ist nichts zu sehen ausser:

`<html>
<body>

doorbird.0 | 2023-07-13 12:21:15.147 | debug | Snapshot saved successfully!
-- | -- | -- | --
doorbird.0 | 2023-07-13 12:21:15.122 | info | Trying to take snapshot..

</body>
</html>`

![Unbenannt](https://github.com/iobroker-community-adapters/ioBroker.doorbird/assets/38273154/55d0bb6a-e73f-476d-93a3-e25efd15bab0)

**Versions:**  
 - Adapter version: 1.0.5
 - JS-Controller version: 5.0.7
 - Node version: v18.16.1
 - Operating system: Debian 12

**Comment by mcm1957** [comment]
Dass die Bilder seid 1.0.0 anders abgelegt werden, hast du gesehen?
Siehe auch: https://github.com/iobroker-community-adapters/ioBroker.doorbird/issues/21

**Comment by Schmakus** [comment]
Auch zu finden unter:

/opt/iobroker/iobroker-data/files/doorbird.1
Doorbell1_1.jpg

**Comment by quorle** [comment]
Habe ich alles geprüft, die Bilddateien haben alle 0 Kb

**Comment by Schmakus** [comment]
Wird gecheckt.

**Comment by Schmakus** [comment]
Ich kann das Problem nicht bestätigen. 
Bilder gelöscht. Motion, Doorbell und Snapshot werden alle erstellt bei Ereignis.

**Comment by gaga191281** [comment]
Hallo zusammen. Die Bilder werden bei mir erzeugt und unter dem neuen Pfad abgespeichert. Ich habe nun jedoch das Problem dass meine Vis, welche über den FullyKiosk Browser geladen wird, nicht darauf zugreifen kann, da man sich nun beim ioBroker anmelden muss damit das Bild geladen wird.
Gibt es dafür einen Workaround??

**Comment by Schmakus** [comment]
> Hallo zusammen. Die Bilder werden bei mir erzeugt und unter dem neuen Pfad abgespeichert. Ich habe nun jedoch das Problem dass meine Vis, welche über den FullyKiosk Browser geladen wird, nicht darauf zugreifen kann, da man sich nun beim ioBroker anmelden muss damit das Bild geladen wird.
> Gibt es dafür einen Workaround??

@gaga191281 Verstehe ich das richtig, dass dein ioBroker mit Username und Passwort geschützt ist?
Über `http://<ioBroker-IP>:<Port>/files/doorbird.<instance>.Doorbell<number>_1.jpg` wird kein Bild in der VIS angezeigt?

Evtl. mal versuchen, den username und Passwort in die URL zu integrieren:
`http://<username>:<passwort>@<ioBroker-IP>:<Port>/files/doorbird.<instance>.Doorbell<number>_1.jpg`

**Comment by gaga191281** [comment]
> > Hallo zusammen. Die Bilder werden bei mir erzeugt und unter dem neuen Pfad abgespeichert. Ich habe nun jedoch das Problem dass meine Vis, welche über den FullyKiosk Browser geladen wird, nicht darauf zugreifen kann, da man sich nun beim ioBroker anmelden muss damit das Bild geladen wird.
> > Gibt es dafür einen Workaround??
> 
> @gaga191281 Verstehe ich das richtig, dass dein ioBroker mit Username und Passwort geschützt ist? Über `http://<ioBroker-IP>:<Port>/files/doorbird.<instance>.Doorbell<number>_1.jpg` wird kein Bild in der VIS angezeigt?
> 
> Evtl. mal versuchen, den username und Passwort in die URL zu integrieren: `http://<username>:<passwort>@<ioBroker-IP>:<Port>/files/doorbird.<instance>.Doorbell<number>_1.jpg`

Fehler meinerseites ich habe unter der vollen Addresse aus der Vis auf das Bild zugegriffen (http://192....) anstelle von (/doorbird.0/...).
Jetzt gehts.

**Comment by Schmakus** [comment]
noch aktuell?

**Comment by quorle** [comment]
Jetzt funktioniert alles.
