### ISSUE TITLE
Fehlende Bilder bei Mehrparteienanlage

### ISSUE THREAD

**Issue by zahnheinrich** [iobroker-community-adapters/ioBroker.doorbird#68]
Seit der Version 1.0.5 werden nach Druck auf die einzige Klingeltaste einer Doorbird D2101 Bilder in /iobroker-data/files/doorbird.0 gespeichert als Doorbell1_1.jpg, was auch einwandfrei geht.

Bei meiner D2103V mit drei Klingeltasten wird immer ein Bild Doorbell102_1.jpg abgelegt, egal welche Klingel gedrückt wird.

Erwarten würde ich bei Tastendruck Klingel 1 (doorbird.0.Doorbell.101.trigger ausgelöst!) ein Bild Doorbell101_1.jpg, bei Tastendruck Klingel 2 (doorbird.0.Doorbell.102.trigger ausgelöst!) ein Bild Doorbell102_1.jpg und bei Tastendruck Klingel 3 (doorbird.0.Doorbell.103.trigger ausgelöst!) ein Bild Doorbell103_1.jpg 

Edit:  Nach nochmaliger Prüfung Geht das wie es soll, also KEIN isuue

**Comment by Schmakus** [comment]
Hast du dir mal die Zeitpläne in der Doorbird App angeschaut, ob die passen?
Werden die Datenpunkte richtig getriggert?
