### ISSUE TITLE
js-controller (>=4.1.0): 4.0.24

### ISSUE THREAD

**Issue by Horgul123** [iobroker-community-adapters/ioBroker.doorbird#69]
Is there an error in the minimum js-controller version?
4.0.24 seems to be the latest 4.x version ( see https://github.com/ioBroker/ioBroker.js-controller/blob/master/CHANGELOG.md )

**Comment by mcm1957** [comment]
@Schmakus 
@Apollon77

Requiring js-controller 4.1.x is definittly an error.
Please check asap if this requirment only blocks latest 1.1.0 or stable release 1.0.6 released today as hot fix.

@Schmakus 
Why did you increase js-controlelr requirement at all?

**Comment by Apollon77** [comment]
In fact this requirements leads to js-controller 5.0.x only ... and yes this would conflict with stable because js.controller 5 is still latest

**Comment by mcm1957** [comment]
Yes stable release 1.0.6 is effected too.

**Comment by mcm1957** [comment]
@Schmakus 

Ich habe STABLE auf 1.0.5 downgegraded. Bitte erstell - falls wirklich notwendig - eine neue 1.0.7 NUR mit deinem Hofix. Und bitte in einem Hotfix nur ändern was absolut notwendig ist - insbesondere wenn diese Release nicht in latest kommen kann da es dort schon eine höhere Release gibt. 

Bei einem Hotfix zählt - je weniger Zeilen geändert desto besser. Ein generelles Update der dependencies ist i.A, kein Hotfix, da solche eine Änderung wohl einige Tage im Latest erfordert.

Und was 1.1.0 betrifft: 
Warum wird hier js-controller 5 (oder der latest js-controler 4) required? Wenn dann muss das auch in die Releasenotes rein. Generell sollten user aber nicht unnötig gezwungen werden den js-controller zu aktualisiseren.

ERGO:
Bitte entweder einen Hotfix erstellen, der nur die notwendigesten Codeänderungen enthält (und keine generellen Updates der dependencies, Erweiterungen etc) ODER eine neue normale Release erstellen, die dependencies updated und Dinge fixed. Diese sollte dann ganz normal in Latest und später in Stabel gehen.

Danke
McM1957

@Apollon (FYI only)

**Comment by Schmakus** [comment]
v1.1.1 ist num im latest. v1.0.5 bleibt bis auf weiteres im Stable, da der Speicherüberlauf nur sporadisch bei einem user aufgetreten ist.

**Comment by mcm1957** [comment]
Danke f.d. Info und den schnellen fix.
