### ISSUE TITLE
Adapter startet nicht nach Update auf V1.1.1

### ISSUE THREAD

**Issue by data2000** [iobroker-community-adapters/ioBroker.doorbird#70]
Der Doorbird Adapter läuft nach dem Update auf V1.1.1 auf nachfolgende Fehler und startet nicht mehr.
Installation:
Admin 6.6.3
Node.js v18.17.0
NPM 6.14.10

Was kann ich tun?

<html>
<body>

host.Rpi4 | 2023-08-07 13:55:23.608 | error | instance system.adapter.doorbird.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.Rpi4 | 2023-08-07 13:55:23.608 | error | Caught by controller[0]: Node.js v18.17.0
host.Rpi4 | 2023-08-07 13:55:23.608 | error | Caught by controller[0]: }
host.Rpi4 | 2023-08-07 13:55:23.607 | error | Caught by controller[0]: ]
host.Rpi4 | 2023-08-07 13:55:23.607 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.doorbird/main.js'
host.Rpi4 | 2023-08-07 13:55:23.607 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.doorbird/node_modules/@iobroker/adapter-core/build/index.js',
host.Rpi4 | 2023-08-07 13:55:23.607 | error | Caught by controller[0]: requireStack: [
host.Rpi4 | 2023-08-07 13:55:23.607 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.Rpi4 | 2023-08-07 13:55:23.607 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1143:19) {
host.Rpi4 | 2023-08-07 13:55:23.607 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:960:12)
host.Rpi4 | 2023-08-07 13:55:23.607 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1119:32)
host.Rpi4 | 2023-08-07 13:55:23.606 | error | Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
host.Rpi4 | 2023-08-07 13:55:23.606 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1256:14)
host.Rpi4 | 2023-08-07 13:55:23.606 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.doorbird/node_modules/@iobroker/adapter-core/build/index.js:21:1)
host.Rpi4 | 2023-08-07 13:55:23.606 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:110:18)
host.Rpi4 | 2023-08-07 13:55:23.606 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1143:19)
host.Rpi4 | 2023-08-07 13:55:23.606 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:922:27)
host.Rpi4 | 2023-08-07 13:55:23.606 | error | Caught by controller[0]: at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
host.Rpi4 | 2023-08-07 13:55:23.605 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.doorbird/main.js
host.Rpi4 | 2023-08-07 13:55:23.605 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.doorbird/node_modules/@iobroker/adapter-core/build/index.js
host.Rpi4 | 2023-08-07 13:55:23.605 | error | Caught by controller[0]: Require stack:
host.Rpi4 | 2023-08-07 13:55:23.605 | error | Caught by controller[0]: Error: Cannot find module '@iobroker/types'
host.Rpi4 | 2023-08-07 13:55:23.605 | error | Caught by controller[0]: ^
host.Rpi4 | 2023-08-07 13:55:23.605 | error | Caught by controller[0]: throw err;
host.Rpi4 | 2023-08-07 13:55:23.604 | error | Caught by controller[0]: node:internal/modules/cjs/loader:1080

</body>
</html>

Vielen Dank schon einmal.
VG
Volker

**Comment by data2000** [comment]
Vielen Dank. Da passten noch Links unter /usr/bin und /usr/local/bin nicht.
NPM ist nun V9.6.1

Doorbird startet aber leider noch immer nicht 

<html>
<body>


host.Rpi4 | 2023-08-07 15:09:26.134 | error | instance system.adapter.doorbird.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.Rpi4 | 2023-08-07 15:09:26.134 | error | Caught by controller[0]: Node.js v18.17.0
host.Rpi4 | 2023-08-07 15:09:26.133 | error | Caught by controller[0]: }
host.Rpi4 | 2023-08-07 15:09:26.133 | error | Caught by controller[0]: ]
host.Rpi4 | 2023-08-07 15:09:26.133 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.doorbird/main.js'
host.Rpi4 | 2023-08-07 15:09:26.133 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.doorbird/node_modules/@iobroker/adapter-core/build/index.js',
host.Rpi4 | 2023-08-07 15:09:26.133 | error | Caught by controller[0]: requireStack: [
host.Rpi4 | 2023-08-07 15:09:26.133 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.Rpi4 | 2023-08-07 15:09:26.133 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1143:19) {
host.Rpi4 | 2023-08-07 15:09:26.132 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:960:12)
host.Rpi4 | 2023-08-07 15:09:26.132 | error | Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1119:32)
host.Rpi4 | 2023-08-07 15:09:26.132 | error | Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
host.Rpi4 | 2023-08-07 15:09:26.132 | error | Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1256:14)
host.Rpi4 | 2023-08-07 15:09:26.132 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.doorbird/node_modules/@iobroker/adapter-core/build/index.js:21:1)
host.Rpi4 | 2023-08-07 15:09:26.132 | error | Caught by controller[0]: at require (node:internal/modules/cjs/helpers:110:18)
host.Rpi4 | 2023-08-07 15:09:26.132 | error | Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1143:19)
host.Rpi4 | 2023-08-07 15:09:26.131 | error | Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:922:27)
host.Rpi4 | 2023-08-07 15:09:26.131 | error | Caught by controller[0]: at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
host.Rpi4 | 2023-08-07 15:09:26.131 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.doorbird/main.js
host.Rpi4 | 2023-08-07 15:09:26.131 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.doorbird/node_modules/@iobroker/adapter-core/build/index.js
host.Rpi4 | 2023-08-07 15:09:26.131 | error | Caught by controller[0]: Require stack:
host.Rpi4 | 2023-08-07 15:09:26.131 | error | Caught by controller[0]: Error: Cannot find module '@iobroker/types'
host.Rpi4 | 2023-08-07 15:09:26.130 | error | Caught by controller[0]: ^
host.Rpi4 | 2023-08-07 15:09:26.130 | error | Caught by controller[0]: throw err;
host.Rpi4 | 2023-08-07 15:09:26.130 | error | Caught by controller[0]: node:internal/modules/cjs/loader:1080


</body>
</html>

**Comment by Schmakus** [comment]
Welche js-controller Version hast du?

**Comment by data2000** [comment]
Herzlichen Dank Schmakus.
Ich habe eine Lösung gefunden, indem ich im Adapterverzeichnis
```
cd /opt/iobroker/node_modules/iobroker.doorbird/
sudo npm install --production
```
ausführte. 
Dabei zeigte er mir auch an, dass eine neue Node Version verfügbar wäre (v9.8.1), welche ich auch gleich installierte.
Also so...

```
sudo npm install -g npm@9.8.1
sudo npm install --production
```

Das klappte auch beim Web Adapter.

**Jetzt läuft alles wieder.**
Nun kann dieser Issue auf jeden Fall geschlossen werden.
**Vielen Dank für Deine Hilfe.**

**Comment by Schmakus** [comment]
Also. Das Problem wird NPM 6 zum Zeitpunkt der Updates gewesen sein. 
Da nun npm 9 drauf hast, musst die Adapter ganz löschen und neu installieren.
