### ISSUE TITLE
"ListenOnAllInterfaces" Not working

### ISSUE THREAD

**Issue by Stefan592** [iobroker-community-adapters/ioBroker.doorbird#74]
Hi,

deine Änderung [hier](https://github.com/iobroker-community-adapters/ioBroker.doorbird/blob/92a4cb457955d49fd08a51ddcc8985135c00cd28/main.js#L101C52-L101C74) funktionieret leider nicht.

Im "res.socket.remoteAddress" enthält die IP von der die Anfrage kommt. In einen BridedLan ist es die Adresse des "Routers" der die Bridge macht. 

Die Angabe von '0.0.0.0' bei server.listen bewirkt das auf allen Interfaces gehört wird, '0.0.0.0' kann und wird aber niemals der Wert von "res.socket.remoteAddress" sein.

Bitte ändere die entsprechende [Zeile](https://github.com/iobroker-community-adapters/ioBroker.doorbird/blob/92a4cb457955d49fd08a51ddcc8985135c00cd28/main.js#L101C52-L101C74) auf:

`
if (remoteAddress === this.config.birdip || this.config.listenOnAllInterfaces) {
`

Damit wird die IP Prüfung deaktiviert wenn 'listenOnAllInterfaces' aktiviert ist. Und das Feature "ListenOnAllInterfaces" funktioniert.

Hier ein Debug aus IoBroker:

![image](https://github.com/iobroker-community-adapters/ioBroker.doorbird/assets/14180760/57111816-2327-4d06-b115-a88025916350)
![image](https://github.com/iobroker-community-adapters/ioBroker.doorbird/assets/14180760/aa1efc58-8339-45b4-b948-83fa590d582b)

Netzwerkaufbau:
![image](https://github.com/iobroker-community-adapters/ioBroker.doorbird/assets/14180760/e8ff1c4e-dc6a-402d-8356-359426617e50)

**Comment by Schmakus** [comment]
Ok, wenn es so bei dir funktioniert. Machst ein PR?
