### ISSUE TITLE
Doorbell.1.trigger springt auf True bei Codeeingabe

### ISSUE THREAD

**Issue by skyx3** [iobroker-community-adapters/ioBroker.doorbird#76]
Ich habe eine DoorBird D1101KV, wenn ich den Klingel Taster bediene springt der Datenpunkt:

doorbird.0.Doorbell.1.trigger

auf true. Soweit auch OK. Gebe ich aber einen Code ins Keypad ein, egal welchen (es gibt 6) springt der Datenpunkt ebenfalls immer auf true und damit werden auch die Rules getriggert die mit dem Datenpunkt verbunden sind.

**Comment by Schmakus** [comment]
Als erstes prüfe deine Favoriten und Zeitpläne in der Doorbird-App, ob da bei Codeeingabe ein Zeitplan hinterlegt ist, welchen den HTTP Request auslöst.
Ansonsten mal ein debug-log hier posten.

**Comment by Schmakus** [comment]
Pro HTTP-Request (Favorite) kann ein Zeitplan angelegt werden. Wenn natürlich der DoorBell Favorite getriggert wird, bei Code-Eingabe, dann ist das die logische Konsequenz. :-)

**Comment by skyx3** [comment]
JA OK das ist es, das war mir nicht klar. Ich bin davon ausgegangen man wählt immer nur eine Aktion und einen Zeitplan aus, das ich theoretisch hinter einen Code auch einfach alle Datenpunkt gleichzeitig triggern kann, war mir nicht bewusst. OK in dem Fall war wirklich bei der Code Eingabe der Klingel Trigger hinterlegt. Danke für die super schnelle Hilfe. Das hat Doorbird wirklich nicht verständlich beschrieben, aber jetzt weiß ich es ja :-)
