### ISSUE TITLE
No "Doorbell-Option" in IoBroker Objects

### ISSUE THREAD

**Issue by DennisH1978** [iobroker-community-adapters/ioBroker.doorbird#8]
Hallo zusammen!
Ich habe mir eine Doorbird D2101V zugelegt und auch gleich den Adapter 0.1.5. installiert.
Leider fehlt mir unter "Objekte" der Ordner "Doorbell". Er hat selbst nach dem zweiten mal installieren, nur "Motion", "Relays" und "Info" angelegt. Ich habe im Adapter alles korrekt ausgefüllt, er erscheint auch grün, alles ist "wahr". Was kann hier falsch gelaufen sein?
Gruß Dennis

**Comment by Nickybroke** [comment]
Selbes Problem bei mir. Doorbird ist nicht nutzbar. Sehr schade. Wieder ein Stück iobroker weniger......

**Comment by Schmakus** [comment]
Selbes Problem.

**Comment by frank2604** [comment]
Bei mir auch. Bei der Erstinstallation hat er noch alle Datenpunkte angelegt, inkl. Doorbell. Dann musste ich einen Werksreset vor der Doorbird machen. Adapterinstanz gelöscht und neu installiert - seither leider auch kein DP "Doorbell" mehr. Er legt auch in den HTTP-Calls nur noch den Aufruf für Motion an, nicht mehr den für Ring.

Muss ich es eben mit manuellen HTTP Calls, dem Simple-API-Adapter und Skripten lösen, so wie für die Relaissteuerung.

Schade dass sich hier keiner mehr kümmert.

**Comment by SmartNightly** [comment]
Hallo, habe die D1101V und selbes Problem hier. DP "Doorbell" existiert nicht. Wird auch bei Deinstallation und Neuinstallation des Adapters nicht angelegt. Schade, habe mich extra wegen des Adapters für einen DB entschieden.

**Comment by SmartNightly** [comment]
Hi all, wenn ihr keinen Dorbell DP habt, müsst ihr in der App einen "Zeitplan für Türkliongel" für "HTTP(S) Aufrufe" erstellen (Dropdown oben links ändern". Adapter neu starten, dann wird ein neuer DP erstellt.

**Comment by pacco81** [comment]
Ich hatte auch das Problem und nach Anlage eines Zeitplans für HTTP klappte es. Besten Dank Smart Nightly
