### ISSUE TITLE
Eigene HTTPS Aufrufe hinzufügen

### ISSUE THREAD

**Issue by kevinhaybach** [iobroker-community-adapters/ioBroker.doorbird#82]
In der Doorbird-App kann man eigene HTTP(S) Aufrufe hinzufügen. Für den iobroker-Adapter gibt es aktuell den Ring und Motion Aufruf. Es wäre schön wenn man noch weitere Aufrufe hinzufügen könnte, die dann von dem iobroker-Adapter ausgewertet werden

Mit freundlichen Grüßen
Kevin

**Comment by Negalein** [comment]
funktioniert mit Simple-API.

Hier ein Beispiel um den RFID auszuwerten.
http://10.0.1.202:8087/toggle/0_userdata.0.Doorbird.RFID.Laura

:8087 ist der Simple-API Port.

**Comment by Schmakus** [comment]
> In der Doorbird-App kann man eigene HTTP(S) Aufrufe hinzufügen. Für den iobroker-Adapter gibt es aktuell den Ring und Motion Aufruf. Es wäre schön wenn man noch weitere Aufrufe hinzufügen könnte, die dann von dem iobroker-Adapter ausgewertet werden
> 
> 
> 
> Mit freundlichen Grüßen
> 
> Kevin

Hi, an was hast da gedacht?
Der Adapter bedient eigentlich nur die API Schnittstelle von DoorBird. RFID ist in Planung. 

Alles andere wie oben beschrieben mit simpleApi möglich.

**Comment by kevinhaybach** [comment]
Simple API kannte ich noch nicht löst aber alle meine Probleme von daher ist dieses Enhancement für meine Anwendung nicht mehr nötig.

Vielen Dank für die schnelle Hilfe

**Comment by Negalein** [comment]
> Simple API kannte ich noch nicht löst aber alle meine Probleme von daher ist dieses Enhancement für meine Anwendung nicht mehr nötig.

rein aus Interesse. Welche HTTP(S) Aufrufe machst du?

**Comment by kevinhaybach** [comment]
In der Doorbird App kann man das Relais Auslösen um die Tür zu öffnen. Ich habe die Tür aber nicht ans Relay direkt angeschlossen sondern an meine SPS. Der HTTPS-Aufruf triggert iobroker der wiederrum über MODBUS die SPS triggert.
Hier wäre wirklich noch eine Verbesserung für den Doorbird-Adapter möglich. Ich habe nämlich das Motion-Bit missbrauchen müssen um mein Relay-Signal zum IOBroker zu bekommen.
In Zukunft werde ich aber noch weitere Signale hinzufügen
- Haustür öffnen
- Garage öffnen
- Garage schließen

-

**Comment by Schmakus** [comment]
Das Motion-Bit? Musst mir erklären. 
Es geht auch, indem man ein nicht verwendetes Relais der DoorBird nutzt und dafür einen Zeitplan erstellt, was den HTTP Aufruf auslöst. So hab ich es gemacht.

**Comment by kevinhaybach** [comment]
Der Doorbird Adapter erstellt die beiden Bits Doorbell.1.Trigger und Motion.Trigger die dann über die HTTPS Aufrufe htttp://IP-Adresse:8100/ring?1 und http://IP-Adresse:8100/motion aufgerufen werden.
Ich habe nun einen Zeitplan erstellt der wie du schon sagst den HTTP Aufruf genommen und das Motion BIT missbraucht. Hätte der Doorbird Adapter hier noch ein weiteres BIT angelegt hätte ich das Motion Bit nicht missbrauchen müssen. 
Durch SimpleAPI kann ich aber nun komplett auf den Doorbird-Adapter verzichten
