### ISSUE TITLE
no snapshot available in /opt/iobroker/iobroker-data/doorbird.0.snap.jpg

### ISSUE THREAD

**Issue by mibr85** [iobroker-community-adapters/ioBroker.doorbird#90]
**Describe the bug**  
since i reinstall my ioBroker, i get the ring signal from doorbird but there are no snapshot saved anymore.
i reinstalled the adapter, but the behavior is the same.
state snapshot is not shown anymore
![grafik](https://github.com/iobroker-community-adapters/ioBroker.doorbird/assets/56867583/56ce7d33-d1e4-4a7e-baf3-60d38861daa8)

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
Plattform:     docker
Betriebssystem:     linux
Architektur:     x64
CPUs:     4
Geschwindigkeit:     800 MHz
Modell:     AMD GX-412TC SOC
RAM:     3.85 GB
System-Betriebszeit:    12 T. 22:22:32
Node.js    v18.17.1 (Es gibt eine neuere Version: v18.18.0)
NPM    9.6.7
admin: 6.10.1
host: 5.0.12

**Comment by Schmakus** [comment]
It's not a bug! 
Do you have read the news during installation or the readme?
The images are now located at ioBroker files!

**Comment by Negalein** [comment]
> state snapshot is not shown anymore

https://github.com/iobroker-community-adapters/ioBroker.doorbird#access-to-the-snapshots-of-motion-and-doorbell

**Comment by mibr85** [comment]
sorry i have missed this information.
it worked now .
Thanks a lot
