### ISSUE TITLE
[Feature Request] Steuerung von Peripherie (Gong)

### ISSUE THREAD

**Issue by Hant0r** [iobroker-community-adapters/ioBroker.doorbird#99]
Wäre es möglich, über den Adapter auch Peripherie-Geräte wie einen Doorbird-Gong zu steuern?
In der App geht das ja.

Würde gerne die Lautstärke automatisiert anpassen können oder ihn ganz ausstellen, wenn z. B. die Kids schlafen.

Gruß

**Comment by Schmakus** [comment]
Hi,
leider wird der Gong von der API nicht unterstützt. 😔
Hatte entsprechend schon Kontakt mit Doorbird. 
Ich vermisse die Funktion auch.

**Comment by Hant0r** [comment]
Ach Mist. Hat der Gong evtl. eine eigene API?
Hat ja auch eine eigene IP Adresse 🤷

**Comment by Schmakus** [comment]
Auch nicht. Sonst hätte ich das längst implementiert.

**Comment by Hant0r** [comment]
Hmm, das ist traurig. Kann man bei Doorbird seinen Bedarf melden damit sich was ändert?

**Comment by Hant0r** [comment]
Alles klar, mal sehen was zurück kommt. Je mehr danach fragen, desto eher wird vielleicht die Chance sein, dass etwas umgesetzt wird 🤷

**Comment by Hant0r** [comment]
Also nett ist der Support auf jedenfall. 
Hier meine Antwort die ich bekommen habe:

> Hallo,
> 
> vielen Dank für Ihre Nachricht.
> 
> Es gab dazu in der Vergangenheit mal einen Kundenwunsch dazu, daher wurde das Thema bereits besprochen, den Türgong generell Teil der API werden zu lassen. Es wurde aber mit sehr geringer Priorität eingeordnet, d.h. es ist denkbar, dass es irgendwann kommt, aber keinesfalls zeitnah.
> 
> Mit freundlichen Grüßen
> DoorBird Team

Auf weiter Nachfrage, wie man die interne Priorität erhöhen kann und es sich auch bestimmt Andere darüber freuen würden, kam nur zurück, dass die Prio nicht beeinflusst werden könnte (zumindest nicht von ihm) und dass die Nutzer wesentlich weniger sind als ich glauben würde. 
Heißt für mich, es müssen sich einfach noch mehr mit den Frage an den Support wenden. Je häufiger die Anfrage kommt, desto besser :)

Gr€€tz
